@CryptoBank_WebApi_HostAddress = http://localhost:5055
@AccessToken = {{jwt}}
@RefreshToken = {{refreshToken}}

### UserNews
GET {{CryptoBank_WebApi_HostAddress}}/usernews/
Accept: application/json
Authorization: Bearer {{AccessToken}}

### AdminNews
GET {{CryptoBank_WebApi_HostAddress}}/adminnews/
Accept: application/json
Authorization: Bearer {{AccessToken}}

### AllNews
GET {{CryptoBank_WebApi_HostAddress}}/allnews/
Accept: application/json
Authorization: Bearer {{AccessToken}}

### Auth
POST {{CryptoBank_WebApi_HostAddress}}/auth/
Content-Type: application/json

{
  "Email": "user1@admin.com",
  "Password": "123"
}

> {% 
    client.global.set("jwt", response.body.jwt);
    client.global.set("RefreshToken", response.headers['Set-Cookie']);
%}

### SignUp
POST {{CryptoBank_WebApi_HostAddress}}/signup/
Content-Type: application/json

{
  "Email": "newuser2@admin.com",
  "Password": "123",
  "FirstName": "John",
  "LastName": "Doe"
}

### RefreshToken
GET {{CryptoBank_WebApi_HostAddress}}/refresh-token/
Content-Type: application/json
Authorization: Bearer {{AccessToken}}
Cookie: RefreshToken={{RefreshToken}}


