@CryptoBank_WebApi_HostAddress = http://localhost:5055
@AccessToken = {{jwt}}
@RefreshToken = {{refreshToken}}

### SignUp new user
POST {{CryptoBank_WebApi_HostAddress}}/signup/
Content-Type: application/json

{
  "Email": "user1@admin.com",
  "Password": "123",
  "FirstName": "John",
  "LastName": "Doe"
}

### Get News for User
GET {{CryptoBank_WebApi_HostAddress}}/usernews/
Accept: application/json
Authorization: Bearer {{AccessToken}}

> {%
    console.log(response.body);
    console.log(response.headers);
%}

### Get News for Admin
GET {{CryptoBank_WebApi_HostAddress}}/adminnews/
Accept: application/json
Authorization: Bearer {{AccessToken}}

> {%
    console.log(response.body);
    console.log(response.headers);
%}

### Get All News
GET {{CryptoBank_WebApi_HostAddress}}/allnews/
Accept: application/json
Authorization: Bearer {{AccessToken}}

### Get Authentification Token
POST {{CryptoBank_WebApi_HostAddress}}/auth/
Content-Type: application/json

{
  "Email": "user1@admin.com",
  "Password": "123"
}

> {%
    console.log(response.body);
    client.global.set("jwt", response.body.jwt);
    console.log(response.headers);
    client.global.set("refreshToken", response.headers.valueOf('Set-Cookie'));
%}

### Refresh authentification token
GET {{CryptoBank_WebApi_HostAddress}}/refresh-token/
Content-Type: application/json
Authorization: Bearer {{AccessToken}}
Cookie: {{RefreshToken}}

> {%
    console.log(response.body);
    client.global.set("jwt", response.body.jwt);
    console.log(response.headers);
    client.global.set("refreshToken", response.headers.valueOf('Set-Cookie'));
%}

### Get Authenticated User Profile
GET {{CryptoBank_WebApi_HostAddress}}/user-profile/
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

### Update UserRole
POST {{CryptoBank_WebApi_HostAddress}}/user-role/
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

{
  "UserId": 2,
  "Role": "Administrator"
}

### Dictionary UserRoles
GET {{CryptoBank_WebApi_HostAddress}}/dictionary/user-roles/
Content-Type: application/json

### Create Account
POST {{CryptoBank_WebApi_HostAddress}}/create-account/
Content-Type: application/json
Authorization: Bearer {{AccessToken}}

### Get user accounts
GET {{CryptoBank_WebApi_HostAddress}}/user-accounts/
Content-Type: application/json
Authorization: Bearer {{AccessToken}}


